### ISSUE TITLE
What are the curation rules?

### ISSUE THREAD

**Issue by jdhitsolutions** [janikvonrotz/awesome-powershell#53]
How is this list maintained or curated?  Do you expect people to fork and submit PRs? Use an Issue to report a bad link or a suggestion for new sources?

**Comment by janikvonrotz** [comment]
Hi, sorry for the delay. The list is not maintained regularly and I have rather added new entries than removed them. Mainly because I wanted to see the list growing. People already have contributed to the list and submitted PRs. If you have found a bad link or think an entry should be removed, I would love to hear from you. New suggestions and contributions are always welcome
