### ISSUE TITLE
About the name `modules`

### ISSUE THREAD

**Issue by chantisnake** [janikvonrotz/awesome-powershell#6]
the first sector of the list is called `modules`, but there are some thing definitely not modules in there, like:

- IDEs
- Chocolatey (Package Manager)
- AutoSPInstaller (SharePoint) [I think this is more a script than a module]

and ect. so I suggest changing it to `Modules and Utilities` instead of just `Modules`

**Comment by janikvonrotz** [comment]
Sounds reasonable. Have to admit that my initial content sure is out of date. Where would you draw the line between Utilities and Modules?

**Comment by chantisnake** [comment]
hum, I think Modules is more like plugins, but utilities are apps.

utility is not written in powershell script, but can be used in powershell (like `thefuck` and `choco`). but Modules are installed in the `$env:PSModulePath` and written in powershell language.

That is just my defination.

**Comment by vors** [comment]
Agree. The word "Module" has a strong connotations in the context of PowerShell.
It's better to move IDEs and other non-ps-module things outside or better re-think the organization structure more deeply.

In general, I think that the naming and division is very strict right now.
For example, take a look how many items are in https://github.com/unixorn/awesome-zsh-plugins#plugins and they are not divided into a granular categories. I think it's better, because some things are hard to classify (i.e. [PSReflect](https://github.com/mattifestation/PSReflect) is mainly about security, but it's also a module and is generally useful).
 
It also worth mention that more loose structure will encourage more contributions, because it's way more work to create a category then to add one-line into an existing (loose) one.

**Comment by janikvonrotz** [comment]
@vors I see the problem with "Module". Instead of having Module and Resources as top-level categories I propose to create something like https://github.com/ianstormtaylor/awesome-heroku. Simply using a flat and sorted structure. If necessary also add the classifier in front of the link. The PowerShell repo itself could end up under "Meta", "Source" or whatever suitable. A short introduction on every category might also help new contributors. What do you think?

**Comment by vors** [comment]
@janikvonrotz good thinking, flatter structure is better.
I'd say they have the same problem: there are categories with just one entry (like blogs). Also not sure that labeles in front is a good idea.
I think as a first step, we can remove Module and Resources from the top-level. Maybe rename Resources into "Reading".
Then I'd like to make the categories more loose. If something has 1 or 2 items, maybe it should be generalised.

How that sound?

**Comment by chantisnake** [comment]
I think the flat structure resolves this problem, I will close this issue.

If any one think there is anything wrong with the flat structure, feel free to reopen this issue
